/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Avatar.glb --transform 
Files: public/models/Avatar.glb [3.57MB] > Avatar-transformed.glb [377.77KB] (89%)
*/

import React from 'react'
import { useGraph } from '@react-three/fiber'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'

export function Avatar(props) {
  const group = React.useRef()
  const { scene, animations } = useGLTF('/models/Avatar-transformed.glb')
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { nodes, materials } = useGraph(clone)
  const { actions } = useAnimations(animations, group)

  // Auto-play the first available animation (idle/standing)
  React.useEffect(() => {
    const animationNames = Object.keys(actions)
    if (animationNames.length > 0) {
      actions[animationNames[2]]?.reset().fadeIn(0).play()
    }
  }, [actions])
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" position={[-0.015, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.mixamorigHips} />
        </group>
        <skinnedMesh name="Mesh_0" geometry={nodes.Mesh_0.geometry} material={materials['Material.001']} skeleton={nodes.Mesh_0.skeleton} position={[-0.015, 0, 0]} rotation={[Math.PI / 2, 0, 0]} scale={0.01} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/Avatar-transformed.glb')
